kind: Service
apiVersion: v1
metadata:
  name: ${GOOGLE_PROJECT_ID}-dev
spec:
  selector:
    app: ${GOOGLE_PROJECT_ID}-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${GOOGLE_PROJECT_ID}-dev
  labels:
    app: ${GOOGLE_PROJECT_ID}-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${GOOGLE_PROJECT_ID}-dev
  template:
    metadata:
      labels:
        app: ${GOOGLE_PROJECT_ID}-dev
    spec:
      containers:
        - name: ${GOOGLE_PROJECT_ID}-dev
          image: eu.gcr.io/${GOOGLE_PROJECT_ID}/backendrepo:${CIRCLE_SHA1}
          env:
            - name: DEMO_GREETING
              value: "Hello from the environment"
            - name: DEMO_FAREWELL
              value: "Such a sweet sorrow"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP